import csv
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

REPORT_DIR = Path(__file__).resolve().parents[1] / "reports"
REPORT_DIR.mkdir(parents=True, exist_ok=True)


def generate_csv(case_id: str, evidence_list, out_path: str = None, summary: dict = None, graph_hash: str = None):
    if out_path is None:
        out_path = REPORT_DIR / f"report_{case_id}.csv"
    else:
        out_path = Path(out_path)

    summary = summary or {}
    fieldnames = ["tx_hash", "from", "to", "amount", "asset", "traceable_amount", "unclassified_amount", "timestamp", "vasp", "confidence", "chain"]
    with open(out_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for e in evidence_list:
            writer.writerow({
                "tx_hash": e.get("tx_hash", ""),
                "from": e.get("from", ""),
                "to": e.get("to", ""),
                "amount": e.get("amount", ""),
                "asset": e.get("asset", ""),
                "traceable_amount": e.get("traceable_amount", ""),
                "unclassified_amount": e.get("unclassified_amount", ""),
                "timestamp": e.get("timestamp", ""),
                "vasp": e.get("vasp", ""),
                "confidence": e.get("confidence", ""),
                "chain": e.get("chain", summary.get("chain", "ETH")),
            })
    return str(out_path)


def generate_pdf(case_id: str, evidence_list, out_path: str = None, summary: dict = None, graph_hash: str = None):
    """Generate a readable PDF report from evidence_list. Returns path to PDF file."""
    if out_path is None:
        out_path = REPORT_DIR / f"report_{case_id}.pdf"
    else:
        out_path = Path(out_path)

    doc = SimpleDocTemplate(str(out_path), pagesize=A4, rightMargin=20*mm, leftMargin=20*mm, topMargin=20*mm)
    styles = getSampleStyleSheet()
    story = []

    summary = summary or {}
    graph_hash = graph_hash or "N/A"
    total_value = summary.get('total_value', 0)
    traceable_value = summary.get('traceable_value', 0)
    unclassified_value = summary.get('unclassified_value', 0)
    fraud_probability = summary.get('fraud_probability', summary.get('risk_score', 0))

    story.append(Paragraph(f"CryptoTrace - Investigation Report: {case_id}", styles['Title']))
    story.append(Spacer(1, 6))
    story.append(Paragraph(f"Fraud probability: {fraud_probability}% | Graph hash: {graph_hash}", styles['Normal']))
    story.append(Paragraph(f"Total value: {total_value} ETH | Traceable: {traceable_value} ETH | Unclassified: {unclassified_value} ETH", styles['Normal']))
    story.append(Spacer(1, 8))
    story.append(Paragraph("Generated by CryptoTrace (demo). This report contains blockchain evidence only. The system does NOT identify real persons or access private KYC data.", styles['Normal']))
    story.append(Spacer(1, 12))

    data = [["tx_hash", "from", "to", "amount", "asset", "traceable", "unclassified", "timestamp"]]
    for e in evidence_list:
        data.append([
            (e.get('tx_hash') or '')[:20],
            e.get('from',''),
            e.get('to',''),
            str(e.get('amount','')),
            e.get('asset',''),
            str(e.get('traceable_amount','')),
            str(e.get('unclassified_amount','')),
            str(e.get('timestamp',''))
        ])

    table = Table(data, repeatRows=1)
    table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#2E6DA4')),
        ('TEXTCOLOR',(0,0),(-1,0),colors.white),
        ('GRID', (0,0), (-1,-1), 0.25, colors.grey),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('ALIGN', (3,1), (3,-1), 'RIGHT')
    ]))
    story.append(table)
    story.append(Spacer(1,12))

    story.append(Paragraph("Assessment Summary:", styles['Heading3']))
    story.append(Paragraph(
        "The flow shows multi-layer evidence: traceable routing, unclassified movement, and VASP-linked destination addresses. "
        "This should be treated as a prioritized investigation lead rather than legal proof of identity or criminality.",
        styles['Normal']
    ))
    story.append(Spacer(1,8))

    story.append(Paragraph("Limitations:", styles['Heading3']))
    story.append(Paragraph("This is an investigative lead based on public blockchain data. Attribution uses a conservative FIFO heuristic and address matching against a curated VASP dataset. This output is NOT legal proof of identity or guilt.", styles['Normal']))

    doc.build(story)
    return str(out_path)
