# PowerShell helper to start backend and give instructions for frontend
Write-Host "CryptoTrace demo helper"
Write-Host "1) Backend setup (run once):"
Write-Host "   cd d:\OneDrive\Documents\CRYPTO-TRACE\backend"
Write-Host "   python -m venv .venv"
Write-Host "   .\.venv\Scripts\Activate.ps1"
Write-Host "   python -m pip install -r requirements.txt"
Write-Host "2) Start backend:"
Write-Host "   cd d:\OneDrive\Documents\CRYPTO-TRACE\backend"
Write-Host "   .\.venv\Scripts\python.exe -m uvicorn main:app --reload --port 8000"
Write-Host "3) Frontend setup (run once):"
Write-Host "   cd d:\OneDrive\Documents\CRYPTO-TRACE\frontend"
Write-Host "   npm install"
Write-Host "4) Start frontend dev server (in separate terminal):"
Write-Host "   npm run dev"
Write-Host "5) Use the web UI at http://localhost:5173"
